apiVersion: v1
kind: Pod
metadata:
  name: alberbusybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"]
    resources:
      limits:
        cpu: "0.5"  # 0.5 CPU core
        memory: "512Mi"  # 512 Megabytes
      requests:
        cpu: "0.2"  # 0.2 CPU core
        memory: "256Mi"  # 256 Megabytes